[project]
name = "kurier"
version = "0.1.0"
description = "Django page for listing packages your waiting for"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "ipython>=9.9.0",
    "psycopg>=3.3.4",
]

[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "pre-commit>=4.5.1",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]


[tool.ruff]
line-length = 100

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501"]
